version: '3.1'

services:

  bot_db:
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bot_db
    volumes:
      - ./db/bot:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:8.9.1-community
    #    depends_on:
    #      - db
    ports:
      - "9010:9000"
    networks:
      - sonarnet
    #    environment:
    #      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
    #      SONAR_JDBC_USERNAME: sonar
    #      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./db/sonar/sonarqube_data:/opt/sonarqube/data
      - ./db/sonar/sonarqube_extensions:/opt/sonarqube/extensions
      - ./db/sonar/sonarqube_logs:/opt/sonarqube/logs
      - ./db/sonar/sonarqube_temp:/opt/sonarqube/temp

networks:
  sonarnet:
    driver: bridge
