version: '3.1'

services:

  bot_db:
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bot_db
    volumes:
      - ./bot_db:/var/lib/postgresql/data